#!/usr/bin/env node
// Generates schema/gen/ts/bridge.ts from schema/bridge.schema.json.
//
// Contract-first rule (see README.md): this is the ONLY way gen/ts/bridge.ts
// should ever be produced. Never hand-edit the generated file — edit the
// schema and re-run `npm run gen` instead.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const schemaPath = path.join(here, "bridge.schema.json");
const outDir = path.join(here, "gen", "ts");
const outPath = path.join(outDir, "bridge.ts");

async function main() {
  const raw = await readFile(schemaPath, "utf8");
  const schema = JSON.parse(raw);

  // unreachableDefinitions: emit a named interface/type for every entry in
  // $defs, not just the ones reachable from the root $ref, so e.g. ParamId
  // and SchemaVersion are usable/importable on their own from ui/.
  const ts = await compile(schema, "BridgeMessage", {
    cwd: here,
    unreachableDefinitions: true,
    additionalProperties: false,
    style: { singleQuote: false },
    bannerComment:
      "/* eslint-disable */\n" +
      "/**\n" +
      " * AUTO-GENERATED — DO NOT EDIT BY HAND.\n" +
      " * Generated by schema/gen-types.mjs from schema/bridge.schema.json.\n" +
      " * Run `npm run gen` in schema/ to regenerate after editing the schema.\n" +
      " */",
  });

  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, ts, "utf8");
  console.log(`Wrote ${path.relative(process.cwd(), outPath)} (${ts.length} bytes)`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
